const KEY='minhas-contas-v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{expenses:[{id:crypto.randomUUID(),description:'Aluguel',amount:1800,category:'Moradia',dueDate:new Date().toISOString().slice(0,10),payment:'Pix',status:'pending',recurring:true,notes:''}],budget:5000,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
state.month=new Date(state.month); let editing=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const authUser=JSON.parse(localStorage.getItem('minhas-contas-user')||'null');
function authPanel(id){['auth-login','auth-register','auth-forgot'].forEach(x=>$('#'+x).hidden=x!==id);$('#auth-message').textContent=''}
if(authUser) $('#auth-screen').style.display='none';
$('#show-register').onclick=()=>authPanel('auth-register');$('#show-login').onclick=()=>authPanel('auth-login');$('#forgot-link').onclick=()=>authPanel('auth-forgot');$('#back-login').onclick=()=>authPanel('auth-login');
$('#register-form').onsubmit=e=>{e.preventDefault();if($('#register-password').value!==$('#register-confirm').value)return $('#auth-message').textContent='As senhas não coincidem.';localStorage.setItem('minhas-contas-user',JSON.stringify({name:$('#register-name').value,email:$('#register-email').value}));$('#auth-message').textContent='Cadastro criado. A confirmação por e-mail será ativada quando o Supabase for conectado.';setTimeout(()=>$('#auth-screen').style.display='none',1200)};
$('#login-form').onsubmit=e=>{e.preventDefault();if(!localStorage.getItem('minhas-contas-user'))return $('#auth-message').textContent='Cadastre-se primeiro para entrar.';$('#auth-screen').style.display='none'};$('#forgot-form').onsubmit=e=>{e.preventDefault();$('#auth-message').textContent='Link de recuperação solicitado. Conecte o Supabase para enviar o e-mail real.'};
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const date=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');
function save(){localStorage.setItem(KEY,JSON.stringify({...state,month:state.month.toISOString()}));}
function monthKey(d){const x=new Date(d);return x.getFullYear()===state.month.getFullYear()&&x.getMonth()===state.month.getMonth()}
function statusOf(e){if(e.status==='paid')return'paid';if(new Date(e.dueDate+'T23:59:59')<new Date())return'overdue';return'pending'}
function current(){return state.expenses.filter(e=>monthKey(e.dueDate))}
function render(){const es=current(), total=es.reduce((a,e)=>a+Number(e.amount),0), paid=es.filter(e=>e.status==='paid'), over=es.filter(e=>statusOf(e)==='overdue'), pending=es.filter(e=>statusOf(e)==='pending');$('#month-label').textContent=state.month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,m=>m.toUpperCase());$('#total-month').textContent=money(total);$('#paid-month').textContent=money(paid.reduce((a,e)=>a+Number(e.amount),0));$('#pending-month').textContent=money(pending.reduce((a,e)=>a+Number(e.amount),0));$('#overdue-month').textContent=money(over.reduce((a,e)=>a+Number(e.amount),0));$('#paid-count').textContent=`${paid.length} conta${paid.length===1?'':'s'}`;$('#pending-count').textContent=`${pending.length} conta${pending.length===1?'':'s'}`;$('#overdue-count').textContent=`${over.length} conta${over.length===1?'':'s'}`;$('#donut-total').textContent=money(total).replace(',00','');
 const cats={};es.forEach(e=>cats[e.category]=(cats[e.category]||0)+Number(e.amount));const colors=['#2955d9','#6f87ed','#9eaff5','#c6d0fb','#f0a04b','#78c69a'];let acc=0, entries=Object.entries(cats);$('.donut').style.background=entries.length?'conic-gradient('+entries.map(([c,v],i)=>{const a=acc;acc+=v/total*100;return`${colors[i%colors.length]} ${a}% ${acc}%`}).join(',')+')':'#dce3ff';$('#legend').innerHTML=entries.length?entries.map(([c,v],i)=>`<div><i class="dot" style="background:${colors[i%colors.length]}"></i>${c}<b>${Math.round(v/total*100)}%</b></div>`).join(''):'<span class="muted">Nenhuma despesa neste mês.</span>';
 const upcoming=[...es].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4);$('#upcoming-list').innerHTML=upcoming.length?upcoming.map(e=>`<div class="item"><div class="item-info"><span class="item-icon">${e.category[0]}</span><div><b>${e.description}</b><small class="muted">${date(e.dueDate)}</small></div></div><strong>${money(Number(e.amount))}</strong></div>`).join(''):'<p class="muted">Nenhuma conta cadastrada.</p>';
 $('#recent-list').innerHTML=table(es.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).slice(0,6),false); renderExpenses();renderReports();}
function table(es,full=true){if(!es.length)return'<p class="muted">Nenhum lançamento encontrado.</p>';return`<table class="data-table"><thead><tr><th>Descrição</th><th>Categoria</th><th>Vencimento</th><th>Valor</th><th>Status</th>${full?'<th>Ações</th>':''}</tr></thead><tbody>${es.map(e=>`<tr><td><b>${e.description}</b></td><td>${e.category}</td><td>${date(e.dueDate)}</td><td><b>${money(Number(e.amount))}</b></td><td><span class="status ${statusOf(e)}">${statusOf(e)==='paid'?'Paga':statusOf(e)==='overdue'?'Vencida':'Pendente'}</span></td>${full?`<td><div class="actions"><button class="action-btn" data-edit="${e.id}">Editar</button><button class="action-btn delete" data-delete="${e.id}">Excluir</button></div></td>`:''}</tr>`).join('')}</tbody></table>`}
function renderExpenses(){const q=($('#search')?.value||'').toLowerCase(), sf=$('#status-filter')?.value||'all', cf=$('#category-filter')?.value||'all';$('#expenses-table').innerHTML=table(current().filter(e=>(e.description+e.category).toLowerCase().includes(q)&&(sf==='all'||statusOf(e)===sf)&&(cf==='all'||e.category===cf)));}
function renderReports(){const es=current(), cats={};es.forEach(e=>cats[e.category]=(cats[e.category]||0)+Number(e.amount));let top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$('#top-category').textContent=top?top[0]:'—';let big=es.slice().sort((a,b)=>b.amount-a.amount)[0];$('#top-expense').textContent=big?money(Number(big.amount)):'—';$('#avg-month').textContent=money(es.reduce((a,e)=>a+Number(e.amount),0));const max=top?.[1]||1;$('#report-categories').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="report-row"><span>${c}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<p class="muted">Sem dados.</p>';$('#bar-chart').innerHTML='<div class="bar" style="height:20%"><em>Atual</em><small>'+money(es.reduce((a,e)=>a+Number(e.amount),0))+'</small></div>'}
 function openForm(id){editing=id||null;const e=state.expenses.find(x=>x.id===id);$('#dialog-title').textContent=e?'Editar conta':'Adicionar conta';$('#expense-id').value=id||'';$('#description').value=e?.description||'';$('#amount').value=e?.amount||'';$('#category').value=e?.category||'Moradia';$('#due-date').value=e?.dueDate||new Date().toISOString().slice(0,10);$('#payment').value=e?.payment||'Pix';$('#status').value=e?.status||'pending';$('#recurring').checked=e?.recurring||false;$('#notes').value=e?.notes||'';$('#expense-dialog').showModal()}
 $$('.nav-item,[data-view]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;if(!v)return;$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+v).classList.add('active-view');$('#page-title').textContent={dashboard:'Visão geral',expenses:'Contas e despesas',reports:'Relatórios',settings:'Configurações'}[v];}));['open-add','open-add-2'].forEach(id=>$('#'+id).addEventListener('click',()=>openForm()));$('#expense-form').addEventListener('submit',ev=>{ev.preventDefault();const item={id:editing||crypto.randomUUID(),description:$('#description').value,amount:Number($('#amount').value),category:$('#category').value,dueDate:$('#due-date').value,payment:$('#payment').value,status:$('#status').value,recurring:$('#recurring').checked,notes:$('#notes').value};state.expenses=editing?state.expenses.map(e=>e.id===editing?item:e):[...state.expenses,item];save();$('#expense-dialog').close();render()});['search','status-filter','category-filter'].forEach(id=>$('#'+id).addEventListener('input',renderExpenses));$('#expenses-table').addEventListener('click',e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openForm(edit);if(del&&confirm('Excluir esta conta?')){state.expenses=state.expenses.filter(x=>x.id!==del);save();render()}});$('#prev-month').onclick=()=>{state.month.setMonth(state.month.getMonth()-1);render()};$('#next-month').onclick=()=>{state.month.setMonth(state.month.getMonth()+1);render()};$('#today-btn').onclick=()=>{state.month=new Date();render()};$('#theme-toggle').onclick=()=>document.body.classList.toggle('dark');$('#save-budget').onclick=()=>{state.budget=Number($('#budget-input').value);save();alert('Limite salvo!')};$('#clear-data').onclick=()=>{if(confirm('Apagar todos os lançamentos?')){state.expenses=[];save();render()}};$('#export-csv').onclick=()=>{const rows=[['Descrição','Valor','Categoria','Vencimento','Status'],...current().map(e=>[e.description,e.amount,e.category,e.dueDate,statusOf(e)])];const blob=new Blob([rows.map(r=>r.join(';')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='relatorio-contas.csv';a.click()};
 $('#category-filter').innerHTML='<option value="all">Todas as categorias</option>'+['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Assinaturas','Cartão de crédito','Outros'].map(c=>`<option>${c}</option>`).join('');$('#budget-input').value=state.budget;render();
$$('.nav-item').forEach(button=>button.addEventListener('click',()=>{$$('.nav-item').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));
