const KEY='minhas-contas-v1';
const supabaseClient=window.supabase.createClient('https://niabdewljkfhfzwqglja.supabase.co','sb_publishable_XgH7J_F5vzqs6FrqQxZ8Jw_nZ0a-FQa');let remoteSession=null;
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{expenses:[{id:crypto.randomUUID(),description:'Aluguel',amount:1800,category:'Moradia',dueDate:new Date().toISOString().slice(0,10),payment:'Pix',status:'pending',recurring:true,notes:''}],budget:5000,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
state.month=new Date(state.month); let editing=null;state.income ||= 0;state.categories ||= ['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Assinaturas','Cartão de crédito','Outros'];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function installPayButtons(){document.querySelectorAll('#expenses-table .actions').forEach(box=>{if(box.querySelector('[data-pay]'))return;const row=box.closest('tr');if(!row||row.querySelector('.status')?.classList.contains('paid'))return;const id=box.querySelector('[data-edit]')?.dataset.edit;if(!id)return;const b=document.createElement('button');b.className='action-btn pay';b.dataset.pay=id;b.textContent='Paguei';box.prepend(b)})}new MutationObserver(installPayButtons).observe(document.body,{childList:true,subtree:true});
const budgetCard=document.createElement('article');budgetCard.className='card budget-card';budgetCard.innerHTML='<div class="card-icon purple">◈</div><span>Disponível no limite</span><strong id="available-month">R$ 0,00</strong><small id="budget-label">Limite não definido</small>';$('.cards')?.appendChild(budgetCard);
$('.card.accent span').textContent='Saldo do mês';
const incomeCard=document.createElement('article');incomeCard.className='card income-card';incomeCard.innerHTML='<div class="card-icon green">↗</div><span>Ganho do mês</span><strong id="income-month">R$ 0,00</strong><small>Receita cadastrada</small>';$('.cards')?.insertBefore(incomeCard,budgetCard);
const incomeLabel=document.createElement('label');incomeLabel.innerHTML='Ganho mensal (R$)<input id="income-input" type="number" min="0" step="0.01" placeholder="Ex.: 5000">';$('.settings')?.insertBefore(incomeLabel,$('#budget-input')?.closest('label')||null);
function detectDevice(){document.documentElement.classList.toggle('is-mobile',window.matchMedia('(max-width: 680px)').matches)}detectDevice();window.addEventListener('resize',detectDevice);
const closeAuth=()=>{$('#auth-screen').classList.add('leaving');setTimeout(()=>$('#auth-screen').style.display='none',480)};const authUser=JSON.parse(localStorage.getItem('minhas-contas-user')||'null');supabaseClient.auth.getSession().then(({data})=>{remoteSession=data.session;if(remoteSession){$('#auth-screen').style.display='none';loadRemoteExpenses()}});
async function loadRemoteExpenses(){if(!remoteSession)return;const {data,error}=await supabaseClient.from('expenses').select('*').order('due_date');if(error)return;state.expenses=data.map(e=>({id:e.id,description:e.description,amount:Number(e.amount),category:e.category,dueDate:e.due_date,payment:e.payment_method,status:e.status,recurring:e.recurring,notes:e.notes,paymentDate:e.payment_date}));save();render()}
function authPanel(id){['auth-login','auth-register','auth-forgot'].forEach(x=>$('#'+x).hidden=x!==id);$('#auth-message').textContent=''}
if(authUser) $('#auth-screen').style.display='none';
$('#show-register').onclick=()=>authPanel('auth-register');$('#show-login').onclick=()=>authPanel('auth-login');$('#forgot-link').onclick=()=>authPanel('auth-forgot');$('#back-login').onclick=()=>authPanel('auth-login');
$('#register-form').onsubmit=async e=>{e.preventDefault();if($('#register-password').value!==$('#register-confirm').value)return $('#auth-message').textContent='As senhas não coincidem.';const {error}=await supabaseClient.auth.signUp({email:$('#register-email').value,password:$('#register-password').value,options:{data:{name:$('#register-name').value}}});$('#auth-message').textContent=error?error.message:'Cadastro criado. Confirme seu e-mail para entrar.'};
$('#login-form').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabaseClient.auth.signInWithPassword({email:$('#login-email').value,password:$('#login-password').value});if(error)return $('#auth-message').textContent=error.message;remoteSession=data.session;closeAuth();await loadRemoteExpenses()};$('#forgot-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.resetPasswordForEmail($('#forgot-email').value,{redirectTo:location.origin});$('#auth-message').textContent=error?error.message:'Link de recuperação enviado para seu e-mail.'};
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const date=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');
function save(){localStorage.setItem(KEY,JSON.stringify({...state,month:state.month.toISOString()}));}
function monthKey(d){const x=new Date(d);return x.getFullYear()===state.month.getFullYear()&&x.getMonth()===state.month.getMonth()}
function statusOf(e){if(e.status==='paid')return'paid';if(new Date(e.dueDate+'T23:59:59')<new Date())return'overdue';return'pending'}
function current(){return state.expenses.filter(e=>monthKey(e.dueDate))}setTimeout(()=>{const total=current().reduce((a,e)=>a+Number(e.amount),0);$('#available-month').textContent=money(Math.max(0,state.budget-total));$('#budget-label').textContent=state.budget?`de ${money(state.budget)} definidos`:'Limite não definido'},0)
function updateIncome(){const total=current().reduce((a,e)=>a+Number(e.amount),0);$('#income-month').textContent=money(state.income);$('#income-input').value=state.income;$('#available-month').textContent=money(Math.max(0,(state.income||state.budget)-total));$('#budget-label').textContent=state.income?'ganho menos despesas':(state.budget?`de ${money(state.budget)} definidos`:'Limite não definido')}setTimeout(updateIncome,0);
function render(){const es=current(), total=es.reduce((a,e)=>a+Number(e.amount),0), paid=es.filter(e=>e.status==='paid'), over=es.filter(e=>statusOf(e)==='overdue'), pending=es.filter(e=>statusOf(e)==='pending');$('#month-label').textContent=state.month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,m=>m.toUpperCase());$('#total-month').textContent=money(total);$('#paid-month').textContent=money(paid.reduce((a,e)=>a+Number(e.amount),0));$('#pending-month').textContent=money(pending.reduce((a,e)=>a+Number(e.amount),0));$('#overdue-month').textContent=money(over.reduce((a,e)=>a+Number(e.amount),0));$('#paid-count').textContent=`${paid.length} conta${paid.length===1?'':'s'}`;$('#pending-count').textContent=`${pending.length} conta${pending.length===1?'':'s'}`;$('#overdue-count').textContent=`${over.length} conta${over.length===1?'':'s'}`;$('#donut-total').textContent=money(total).replace(',00','');
 const cats={};es.forEach(e=>cats[e.category]=(cats[e.category]||0)+Number(e.amount));const colors=['#2955d9','#6f87ed','#9eaff5','#c6d0fb','#f0a04b','#78c69a'];let acc=0, entries=Object.entries(cats);$('.donut').style.background=entries.length?'conic-gradient('+entries.map(([c,v],i)=>{const a=acc;acc+=v/total*100;return`${colors[i%colors.length]} ${a}% ${acc}%`}).join(',')+')':'#dce3ff';$('#legend').innerHTML=entries.length?entries.map(([c,v],i)=>`<div><i class="dot" style="background:${colors[i%colors.length]}"></i>${c}<b>${Math.round(v/total*100)}%</b></div>`).join(''):'<span class="muted">Nenhuma despesa neste mês.</span>';
 const upcoming=[...es].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4);$('#upcoming-list').innerHTML=upcoming.length?upcoming.map(e=>`<div class="item"><div class="item-info"><span class="item-icon">${e.category[0]}</span><div><b>${e.description}</b><small class="muted">${date(e.dueDate)}</small></div></div><strong>${money(Number(e.amount))}</strong></div>`).join(''):'<p class="muted">Nenhuma conta cadastrada.</p>';
 $('#recent-list').innerHTML=table(es.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).slice(0,6),false); renderExpenses();renderReports();}
function table(es,full=true){if(!es.length)return'<p class="muted">Nenhum lançamento encontrado.</p>';return`<table class="data-table"><thead><tr><th>Descrição</th><th>Categoria</th><th>Vencimento</th><th>Valor</th><th>Status</th>${full?'<th>Ações</th>':''}</tr></thead><tbody>${es.map(e=>`<tr><td><b>${e.description}</b></td><td>${e.category}</td><td>${date(e.dueDate)}</td><td><b>${money(Number(e.amount))}</b></td><td><span class="status ${statusOf(e)}">${statusOf(e)==='paid'?'Paga':statusOf(e)==='overdue'?'Vencida':'Pendente'}</span></td>${full?`<td><div class="actions"><button class="action-btn" data-edit="${e.id}">Editar</button><button class="action-btn delete" data-delete="${e.id}">Excluir</button></div></td>`:''}</tr>`).join('')}</tbody></table>`}
function renderExpenses(){const q=($('#search')?.value||'').toLowerCase(), sf=$('#status-filter')?.value||'all', cf=$('#category-filter')?.value||'all';$('#expenses-table').innerHTML=table(current().filter(e=>(e.description+e.category).toLowerCase().includes(q)&&(sf==='all'||statusOf(e)===sf)&&(cf==='all'||e.category===cf)));}
function renderReports(){const es=current(), cats={};es.forEach(e=>cats[e.category]=(cats[e.category]||0)+Number(e.amount));let top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$('#top-category').textContent=top?top[0]:'—';let big=es.slice().sort((a,b)=>b.amount-a.amount)[0];$('#top-expense').textContent=big?money(Number(big.amount)):'—';$('#avg-month').textContent=money(es.reduce((a,e)=>a+Number(e.amount),0));const max=top?.[1]||1;$('#report-categories').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="report-row"><span>${c}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<p class="muted">Sem dados.</p>';$('#bar-chart').innerHTML='<div class="bar" style="height:20%"><em>Atual</em><small>'+money(es.reduce((a,e)=>a+Number(e.amount),0))+'</small></div>'}
 function openForm(id){editing=id||null;const e=state.expenses.find(x=>x.id===id);$('#dialog-title').textContent=e?'Editar conta':'Adicionar conta';$('#expense-id').value=id||'';$('#description').value=e?.description||'';$('#amount').value=e?.amount||'';$('#category').value=e?.category||'Moradia';$('#due-date').value=e?.dueDate||new Date().toISOString().slice(0,10);$('#payment').value=e?.payment||'Pix';$('#status').value=e?.status||'pending';$('#recurring').checked=e?.recurring||false;$('#notes').value=e?.notes||'';$('#expense-dialog').showModal()}
 $$('.nav-item,[data-view]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;if(!v)return;$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+v).classList.add('active-view');$('#page-title').textContent={dashboard:'Visão geral',expenses:'Contas e despesas',reports:'Relatórios',settings:'Configurações'}[v];}));['open-add','open-add-2'].forEach(id=>$('#'+id).addEventListener('click',()=>openForm()));$('#expense-form').addEventListener('submit',ev=>{ev.preventDefault();const item={id:editing||crypto.randomUUID(),description:$('#description').value,amount:Number($('#amount').value),category:$('#category').value,dueDate:$('#due-date').value,payment:$('#payment').value,status:$('#status').value,recurring:$('#recurring').checked,notes:$('#notes').value};state.expenses=editing?state.expenses.map(e=>e.id===editing?item:e):[...state.expenses,item];save();$('#expense-dialog').close();render()});['search','status-filter','category-filter'].forEach(id=>$('#'+id).addEventListener('input',renderExpenses));$('#expenses-table').addEventListener('click',e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openForm(edit);if(del&&confirm('Excluir esta conta?')){state.expenses=state.expenses.filter(x=>x.id!==del);save();render()}});$('#prev-month').onclick=()=>{state.month.setMonth(state.month.getMonth()-1);render()};$('#next-month').onclick=()=>{state.month.setMonth(state.month.getMonth()+1);render()};$('#today-btn').onclick=()=>{state.month=new Date();render()};$('#theme-toggle').onclick=()=>document.body.classList.toggle('dark');$('#save-budget').onclick=()=>{state.budget=Number($('#budget-input').value);save();alert('Limite salvo!')};$('#clear-data').onclick=()=>{if(confirm('Apagar todos os lançamentos?')){state.expenses=[];save();render()}};$('#export-csv').onclick=()=>{const rows=[['Descrição','Valor','Categoria','Vencimento','Status'],...current().map(e=>[e.description,e.amount,e.category,e.dueDate,statusOf(e)])];const blob=new Blob([rows.map(r=>r.join(';')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='relatorio-contas.csv';a.click()};
 $('#category-filter').innerHTML='<option value="all">Todas as categorias</option>'+['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Assinaturas','Cartão de crédito','Outros'].map(c=>`<option>${c}</option>`).join('');$('#budget-input').value=state.budget;render();
$$('.nav-item').forEach(button=>button.addEventListener('click',()=>{$$('.nav-item').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));
const categoryButton=document.createElement('button');categoryButton.type='button';categoryButton.id='add-category';categoryButton.className='secondary category-create';categoryButton.textContent='+ Criar categoria';$('#expense-form').insertBefore(categoryButton,$('#expense-form .dialog-actions'));function refreshCategories(){const selected=$('#category')?.value,filter=$('#category-filter')?.value;$('#category').innerHTML=state.categories.map(c=>`<option>${c}</option>`).join('');if(selected&&state.categories.includes(selected))$('#category').value=selected;$('#category-filter').innerHTML='<option value="all">Todas as categorias</option>'+state.categories.map(c=>`<option>${c}</option>`).join('');if(filter&&state.categories.includes(filter))$('#category-filter').value=filter}categoryButton.onclick=()=>{const name=prompt('Nome da nova categoria:');if(!name?.trim())return;const clean=name.trim();if(state.categories.some(c=>c.toLowerCase()===clean.toLowerCase()))return alert('Essa categoria já existe.');state.categories.push(clean);save();refreshCategories();$('#category').value=clean};refreshCategories();
$('#expenses-table').addEventListener('click',e=>{const id=e.target.dataset.pay;if(!id)return;const item=state.expenses.find(x=>x.id===id);if(item){item.status='paid';item.paymentDate=new Date().toISOString().slice(0,10);save();render()}});
$('#income-input')?.addEventListener('change',e=>{state.income=Number(e.target.value)||0;save();updateIncome()});
$('#expense-form').addEventListener('submit',async()=>{const {data:{user}}=await supabaseClient.auth.getUser();const item=state.expenses[state.expenses.length-1];if(!user||!item)return;await supabaseClient.from('expenses').upsert({id:item.id,user_id:user.id,description:item.description,amount:item.amount,category:item.category,due_date:item.dueDate,payment_method:item.payment,status:item.status,recurring:item.recurring,notes:item.notes,payment_date:item.paymentDate||null})});
