const URL='https://niabdewljkfhfzwqglja.supabase.co',KEY='sb_publishable_XgH7J_F5vzqs6FrqQxZ8Jw_nZ0a-FQa';
const db=window.supabase.createClient(URL,KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const defaults=['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Assinaturas','Cartão de crédito','Outros'];
let session=null,editing=null,state={expenses:[],categories:[...defaults],incomes:{},budget:0,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=v=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR');
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,income=()=>Number(state.incomes[monthKey(state.month)]||0);
const current=()=>state.expenses.filter(e=>{const d=new Date(e.dueDate+'T12:00:00');return d.getFullYear()===state.month.getFullYear()&&d.getMonth()===state.month.getMonth()});
const status=e=>e.status==='paid'?'paid':new Date(e.dueDate+'T23:59:59')<new Date()?'overdue':'pending',statusText=s=>({paid:'Paga',pending:'Pendente',overdue:'Vencida'})[s];
function toast(text,type='success'){let el=$('#app-toast');if(!el){el=document.createElement('div');el.id='app-toast';document.body.append(el)}el.className=`app-toast ${type} visible`;el.textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),2600)}
function authPanel(id){['auth-login','auth-register','auth-forgot'].forEach(x=>$('#'+x).hidden=x!==id);$('#auth-message').textContent=''}
function showLogin(){const a=$('#auth-screen');a.classList.remove('leaving');a.style.display='grid';authPanel('auth-login')}
function closeLogin(){const a=$('#auth-screen');a.classList.add('leaving');setTimeout(()=>a.style.display='none',480)}
function refreshCategories(){const selected=$('#category')?.value,filtered=$('#category-filter')?.value;$('#category').innerHTML=state.categories.map(c=>`<option>${c}</option>`).join('');$('#category-filter').innerHTML='<option value="all">Todas as categorias</option>'+state.categories.map(c=>`<option>${c}</option>`).join('');if(selected&&state.categories.includes(selected))$('#category').value=selected;if(filtered&&state.categories.includes(filtered))$('#category-filter').value=filtered}
async function loadData(){if(!session)return;const [er,cr,ir,pr]=await Promise.all([db.from('expenses').select('*').order('due_date'),db.from('categories').select('name').order('name'),db.from('monthly_incomes').select('month,amount'),db.from('profiles').select('monthly_budget').eq('id',session.user.id).maybeSingle()]);if(er.error)return toast('Não foi possível carregar suas contas.','error');state.expenses=er.data.map(e=>({id:e.id,description:e.description,amount:Number(e.amount),category:e.category,dueDate:e.due_date,paymentDate:e.payment_date,payment:e.payment_method,status:e.status,recurring:e.recurring,notes:e.notes||''}));state.categories=cr.error||!cr.data.length?[...defaults]:cr.data.map(c=>c.name);state.incomes={};if(!ir.error)ir.data.forEach(i=>state.incomes[i.month.slice(0,7)]=Number(i.amount));state.budget=Number(pr.data?.monthly_budget||0);$('#budget-input').value=state.budget;refreshCategories();render()}
async function saveExpense(e){const {error}=await db.from('expenses').upsert({id:e.id,user_id:session.user.id,description:e.description,amount:e.amount,category:e.category,due_date:e.dueDate,payment_date:e.paymentDate||null,payment_method:e.payment,status:e.status,recurring:e.recurring,notes:e.notes||null});if(error)throw error}
function table(list,actions=true){if(!list.length)return'<p class="muted empty-state">Nenhum lançamento encontrado.</p>';return`<table class="data-table"><thead><tr><th>Descrição</th><th>Categoria</th><th>Vencimento</th><th>Valor</th><th>Status</th>${actions?'<th>Ações</th>':''}</tr></thead><tbody>${list.map(e=>{const s=status(e);return`<tr><td data-label="Descrição"><b>${e.description}</b></td><td data-label="Categoria">${e.category}</td><td data-label="Vencimento">${date(e.dueDate)}</td><td data-label="Valor"><b>${money(e.amount)}</b></td><td data-label="Status"><span class="status ${s}">${statusText(s)}</span></td>${actions?`<td data-label="Ações"><div class="actions">${s!=='paid'?`<button class="action-btn pay" data-pay="${e.id}">Paguei</button>`:''}<button class="action-btn" data-edit="${e.id}">Editar</button><button class="action-btn delete" data-delete="${e.id}">Excluir</button></div></td>`:''}</tr>`}).join('')}</tbody></table>`}
function renderExpenses(){const q=$('#search').value.toLowerCase(),sf=$('#status-filter').value,cf=$('#category-filter').value;$('#expenses-table').innerHTML=table(current().filter(e=>(e.description+' '+e.category).toLowerCase().includes(q)&&(sf==='all'||status(e)===sf)&&(cf==='all'||e.category===cf)))}
function renderReports(){const list=current(),cats={};list.forEach(e=>cats[e.category]=(cats[e.category]||0)+e.amount);const sorted=Object.entries(cats).sort((a,b)=>b[1]-a[1]),big=[...list].sort((a,b)=>b.amount-a.amount)[0];const totals=[0,1,2].map(n=>{const d=new Date(state.month);d.setMonth(d.getMonth()-n);return state.expenses.filter(e=>{const x=new Date(e.dueDate+'T12:00:00');return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()}).reduce((a,e)=>a+e.amount,0)});$('#avg-month').textContent=money(totals.reduce((a,v)=>a+v,0)/3);$('#top-category').textContent=sorted[0]?.[0]||'—';$('#top-expense').textContent=big?money(big.amount):'—';const max=sorted[0]?.[1]||1;$('#report-categories').innerHTML=sorted.map(([c,v])=>`<div class="report-row"><span>${c}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<p class="muted">Sem dados.</p>';const bars=[0,1,2,3,4,5].map(n=>{const d=new Date(state.month);d.setMonth(d.getMonth()-5+n);return{label:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),total:state.expenses.filter(e=>{const x=new Date(e.dueDate+'T12:00:00');return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()}).reduce((a,e)=>a+e.amount,0)}}),maxBar=Math.max(...bars.map(b=>b.total),1);$('#bar-chart').innerHTML=bars.map(b=>`<div class="bar" style="height:${Math.max(8,b.total/maxBar*100)}%"><em>${money(b.total)}</em><small>${b.label}</small></div>`).join('')}
function render(){const list=current(),total=list.reduce((a,e)=>a+e.amount,0),paid=list.filter(e=>e.status==='paid'),pending=list.filter(e=>status(e)==='pending'),overdue=list.filter(e=>status(e)==='overdue');$('#month-label').textContent=state.month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());$('#total-month').textContent=money(income()-total);$('#paid-month').textContent=money(paid.reduce((a,e)=>a+e.amount,0));$('#pending-month').textContent=money(pending.reduce((a,e)=>a+e.amount,0));$('#overdue-month').textContent=money(overdue.reduce((a,e)=>a+e.amount,0));$('#paid-count').textContent=`${paid.length} conta${paid.length===1?'':'s'}`;$('#pending-count').textContent=`${pending.length} conta${pending.length===1?'':'s'}`;$('#overdue-count').textContent=`${overdue.length} conta${overdue.length===1?'':'s'}`;$('#income-month').textContent=money(income());$('#income-input').value=income()||'';$('#income-reference').textContent=`Referente a ${state.month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}`;const cats={};list.forEach(e=>cats[e.category]=(cats[e.category]||0)+e.amount);const entries=Object.entries(cats),colors=['#5b7cff','#8b6fff','#40c9a2','#f0a04b','#ff7185','#77a8ff'];let acc=0;$('.donut').style.background=entries.length?'conic-gradient('+entries.map(([,v],i)=>{const start=acc;acc+=v/total*100;return`${colors[i%colors.length]} ${start}% ${acc}%`}).join(',')+')':'#1b2940';$('#donut-total').textContent=money(total).replace(',00','');$('#legend').innerHTML=entries.map(([c,v],i)=>`<div><i class="dot" style="background:${colors[i%colors.length]}"></i>${c}<b>${Math.round(v/total*100)}%</b></div>`).join('')||'<span class="muted">Nenhuma despesa neste mês.</span>';const upcoming=[...list].filter(e=>e.status!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4);$('#upcoming-list').innerHTML=upcoming.map(e=>`<div class="item"><div class="item-info"><span class="item-icon">${e.category[0]}</span><div><b>${e.description}</b><small class="muted">${date(e.dueDate)}</small></div></div><strong>${money(e.amount)}</strong></div>`).join('')||'<p class="muted">Nenhuma conta pendente.</p>';$('#recent-list').innerHTML=table([...list].sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).slice(0,6),false);renderExpenses();renderReports()}
function navigate(view){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#view-'+view).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#page-title').textContent={dashboard:'Visão geral',expenses:'Contas e despesas',reports:'Relatórios',settings:'Configurações'}[view]}
function openForm(id=null){editing=id;const e=state.expenses.find(x=>x.id===id);$('#dialog-title').textContent=e?'Editar conta':'Adicionar conta';$('#expense-id').value=id||'';$('#description').value=e?.description||'';$('#amount').value=e?.amount||'';$('#category').value=e?.category||state.categories[0];$('#due-date').value=e?.dueDate||new Date().toISOString().slice(0,10);$('#payment').value=e?.payment||'Pix';$('#status').value=e?.status||'pending';$('#recurring').checked=e?.recurring||false;$('#notes').value=e?.notes||'';$('#expense-dialog').showModal()}
const incomeCard=document.createElement('article');incomeCard.className='card income-card';incomeCard.innerHTML='<div class="card-icon green">↗</div><span>Ganho do mês</span><strong id="income-month">R$ 0,00</strong><small>Receita do mês selecionado</small>';$('.cards').append(incomeCard);$('.card.accent span').textContent='Saldo do mês';
const incomeLabel=document.createElement('label');incomeLabel.innerHTML='Ganho do mês selecionado (R$)<input id="income-input" type="number" min="0" step="0.01" placeholder="Ex.: 5000"><small id="income-reference" class="muted"></small>';$('.settings').insertBefore(incomeLabel,$('#budget-input').closest('label'));
const categoryButton=document.createElement('button');categoryButton.type='button';categoryButton.className='secondary category-create';categoryButton.textContent='+ Criar categoria';$('#expense-form').insertBefore(categoryButton,$('.dialog-actions'));
const logoutButton=document.createElement('button');logoutButton.className='danger-outline';logoutButton.textContent='Sair da conta';$('.settings').append(logoutButton);
$$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#theme-toggle').onclick=()=>navigate('settings');$('#open-add').onclick=()=>openForm();$('#open-add-2').onclick=()=>openForm();$('#prev-month').onclick=()=>{state.month.setMonth(state.month.getMonth()-1);render()};$('#next-month').onclick=()=>{state.month.setMonth(state.month.getMonth()+1);render()};$('#today-btn').onclick=()=>{state.month=new Date(new Date().getFullYear(),new Date().getMonth(),1);render()};['search','status-filter','category-filter'].forEach(id=>$('#'+id).oninput=renderExpenses);document.querySelectorAll('#expense-dialog .close,#expense-dialog button[value="cancel"]').forEach(b=>b.onclick=e=>{e.preventDefault();$('#expense-dialog').close()});
$('#expense-form').onsubmit=async ev=>{ev.preventDefault();const item={id:editing||crypto.randomUUID(),description:$('#description').value.trim(),amount:Number($('#amount').value),category:$('#category').value,dueDate:$('#due-date').value,payment:$('#payment').value,status:$('#status').value,recurring:$('#recurring').checked,notes:$('#notes').value.trim(),paymentDate:state.expenses.find(e=>e.id===editing)?.paymentDate||null};try{await saveExpense(item);state.expenses=editing?state.expenses.map(e=>e.id===editing?item:e):[...state.expenses,item];$('#expense-dialog').close();render();toast(editing?'Conta atualizada e salva.':'Conta criada e salva.')}catch(e){toast('Erro ao salvar: '+e.message,'error')}};
$('#expenses-table').onclick=async ev=>{const {edit,pay,delete:del}=ev.target.dataset;if(edit)return openForm(edit);if(pay){const old=state.expenses.find(e=>e.id===pay),item={...old,status:'paid',paymentDate:new Date().toISOString().slice(0,10)};try{await saveExpense(item);state.expenses=state.expenses.map(e=>e.id===pay?item:e);render();toast('Conta marcada como paga.')}catch(e){toast('Erro ao atualizar: '+e.message,'error')}}if(del&&confirm('Excluir esta conta?')){const {error}=await db.from('expenses').delete().eq('id',del);if(error)return toast('Erro ao excluir: '+error.message,'error');state.expenses=state.expenses.filter(e=>e.id!==del);render();toast('Conta excluída.')}};
categoryButton.onclick=async()=>{const name=prompt('Nome da nova categoria:')?.trim();if(!name)return;if(state.categories.some(c=>c.toLowerCase()===name.toLowerCase()))return toast('Essa categoria já existe.','error');const {error}=await db.from('categories').insert({user_id:session.user.id,name});if(error)return toast('Erro ao criar categoria: '+error.message,'error');state.categories.push(name);state.categories.sort((a,b)=>a.localeCompare(b,'pt-BR'));refreshCategories();$('#category').value=name;toast('Categoria criada e sincronizada.')};
$('#income-input').onchange=async ev=>{const key=monthKey(state.month),amount=Number(ev.target.value||0),{error}=await db.from('monthly_incomes').upsert({user_id:session.user.id,month:key+'-01',amount},{onConflict:'user_id,month'});if(error)return toast('Erro ao salvar ganho: '+error.message,'error');state.incomes[key]=amount;render();toast('Ganho mensal salvo.')};
$('#save-budget').onclick=async()=>{state.budget=Number($('#budget-input').value||0);const {error}=await db.from('profiles').update({monthly_budget:state.budget}).eq('id',session.user.id);error?toast('Erro ao salvar: '+error.message,'error'):toast('Configuração salva.')};
logoutButton.onclick=async()=>{await db.auth.signOut();session=null;state.expenses=[];state.incomes={};showLogin();render()};$('#clear-data').onclick=async()=>{if(!confirm('Apagar todas as suas contas? Esta ação não pode ser desfeita.'))return;const {error}=await db.from('expenses').delete().eq('user_id',session.user.id);if(error)return toast('Erro ao apagar: '+error.message,'error');state.expenses=[];render();toast('Todas as contas foram apagadas.')};
$('#export-csv').onclick=()=>{const rows=[['Descrição','Valor','Categoria','Vencimento','Status'],...current().map(e=>[e.description,e.amount,e.category,e.dueDate,statusText(status(e))])],blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`contas-${monthKey(state.month)}.csv`;a.click();URL.revokeObjectURL(a.href)};
$('#show-register').onclick=()=>authPanel('auth-register');$('#show-login').onclick=()=>authPanel('auth-login');$('#forgot-link').onclick=()=>authPanel('auth-forgot');$('#back-login').onclick=()=>authPanel('auth-login');$('#register-form').onsubmit=async ev=>{ev.preventDefault();if($('#register-password').value!==$('#register-confirm').value)return $('#auth-message').textContent='As senhas não coincidem.';const {error}=await db.auth.signUp({email:$('#register-email').value,password:$('#register-password').value,options:{data:{name:$('#register-name').value}}});$('#auth-message').textContent=error?error.message:'Cadastro criado. Confirme seu e-mail para entrar.'};$('#login-form').onsubmit=async ev=>{ev.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('#login-email').value,password:$('#login-password').value});if(error)return $('#auth-message').textContent=error.message;session=data.session;closeLogin();await loadData()};$('#forgot-form').onsubmit=async ev=>{ev.preventDefault();const {error}=await db.auth.resetPasswordForEmail($('#forgot-email').value,{redirectTo:location.origin});$('#auth-message').textContent=error?error.message:'Link de recuperação enviado para seu e-mail.'};
function adaptNav(){const b=$('[data-view="settings"]');matchMedia('(max-width:680px)').matches?$('.sidebar nav').append(b):$('.sidebar-bottom').prepend(b)}addEventListener('resize',adaptNav);adaptNav();refreshCategories();render();db.auth.getSession().then(async({data})=>{session=data.session;if(session){$('#auth-screen').style.display='none';await loadData()}else showLogin()});
